# Generated by Django 6.0.4 on 2026-04-27 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('intensidade', models.CharField(blank=True, help_text='Ex: Baixa, Média, Alta', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contacto', models.CharField(max_length=15)),
                ('dataNascimento', models.DateField()),
                ('dataAdesao', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=50)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('lotacao', models.IntegerField()),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.modalidade')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.treinador')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('descanso_segundos', models.IntegerField()),
                ('planoTreino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.planotreino')),
            ],
        ),
        migrations.AddField(
            model_name='planotreino',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.socio'),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dataPago', models.DateField()),
                ('estado', models.CharField(choices=[('Liquidado', 'Liquidado'), ('Pendente', 'Pendente')], max_length=20)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRegisto', models.DateField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.aulas')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.socio')),
            ],
        ),
        migrations.AddField(
            model_name='planotreino',
            name='treinador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ginasio.treinador'),
        ),
    ]
