# Generated by Django 6.0.4 on 2026-04-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='dataPago',
            new_name='data_pago',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='estado',
            field=models.CharField(choices=[('Liquidado', 'Liquidado'), ('Pendente', 'Pendente'), ('Atrasado', 'Atrasado')], default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.FloatField(),
        ),
    ]
