# Generated by Django 6.0.4 on 2026-05-05 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0002_rename_datapago_pagamento_data_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='data_vencimento',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='frequencia',
            field=models.CharField(choices=[('Unico', 'Pagamento Único'), ('Mensal', 'Mensalidade')], default='Mensal', max_length=50),
        ),
    ]
