# Generated by Django 6.0.4 on 2026-05-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0003_pagamento_data_vencimento_pagamento_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='descritivo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
