# Generated by Django 6.0.4 on 2026-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0005_socio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='contacto',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dataAdesao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='socios_fotos/'),
        ),
    ]
