# Generated by Django 6.0.4 on 2026-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0007_treinador_user_alter_treinador_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade',
            name='intensidade',
            field=models.CharField(blank=True, help_text='Ex: Baixa, Media, Alta', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='frequencia',
            field=models.CharField(choices=[('Unico', 'Pagamento Unico'), ('Mensal', 'Mensalidade')], default='Mensal', max_length=50),
        ),
    ]
