# Generated by Django 6.0.4 on 2026-06-01 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0008_alter_modalidade_intensidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='planoTreino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ginasio.planotreino'),
        ),
    ]
